spring:
  application:
    name: foreweekdays
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: create-drop

  cloud:
    aws:
      credentials:
        access-key: ${access_key}
        secret-key: ${secret_key}
      s3:
        bucket: ${bucket}
      region:
        static: ap-northeast-2