spring:
  application:
    name: fourweekdays

  config:
    import:
      - optional:classpath:application-db.yml
      - optional:classpath:application-infra.yml
      - optional:classpath:application-management.yml

logging:
  level:
    org.springframework.security: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE