name: Backend Deploy

on:
  push:
    branches: [ "release" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 깃에서 코드를 복사해옴.
      - name: Checkout code via Github
        uses: actions/checkout@v3

      # 2. 빌드에 필요한 Java 17 환경을 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 빌드 전 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 빌드 - 테스트 제외
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 5. EC2로 JAR 파일 전송
      - name: SCP Transfer
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*-SNAPSHOT.jar"
          target: "/home/ubuntu/back/new_deploy"
          strip_components: 2 # build/libs 경로를 제거하고 파일만 전송

      # 6. SSH로 접속해서 기존 프로세스 죽이고 새로 실행
      - name: Execute Remote SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo bash /home/ubuntu/back/deploy.sh
